"""Auto-generated model profiles.

DO NOT EDIT THIS FILE MANUALLY.
This file is generated by the langchain-profiles CLI tool.

It contains data derived from the models.dev project.

Source: https://github.com/sst/models.dev
License: MIT License

To update these data, refer to the instructions here:

https://docs.langchain.com/oss/python/langchain/models#updating-or-overwriting-profile-data
"""

from typing import Any

_PROFILES: dict[str, dict[str, Any]] = {
    "mercury": {
        "name": "Mercury",
        "release_date": "2025-06-26",
        "last_updated": "2025-07-31",
        "open_weights": False,
        "max_input_tokens": 128000,
        "max_output_tokens": 16384,
        "text_inputs": True,
        "image_inputs": False,
        "audio_inputs": False,
        "video_inputs": False,
        "text_outputs": True,
        "image_outputs": False,
        "audio_outputs": False,
        "video_outputs": False,
        "reasoning_output": False,
        "tool_calling": True,
        "attachment": False,
        "temperature": True,
    },
    "mercury-2": {
        "name": "Mercury 2",
        "release_date": "2026-02-24",
        "last_updated": "2026-02-24",
        "open_weights": False,
        "max_input_tokens": 128000,
        "max_output_tokens": 50000,
        "text_inputs": True,
        "image_inputs": False,
        "audio_inputs": False,
        "video_inputs": False,
        "text_outputs": True,
        "image_outputs": False,
        "audio_outputs": False,
        "video_outputs": False,
        "reasoning_output": True,
        "tool_calling": True,
        "structured_output": True,
        "attachment": False,
        "temperature": True,
    },
    "mercury-coder": {
        "name": "Mercury Coder",
        "release_date": "2025-02-26",
        "last_updated": "2025-07-31",
        "open_weights": False,
        "max_input_tokens": 128000,
        "max_output_tokens": 16384,
        "text_inputs": True,
        "image_inputs": False,
        "audio_inputs": False,
        "video_inputs": False,
        "text_outputs": True,
        "image_outputs": False,
        "audio_outputs": False,
        "video_outputs": False,
        "reasoning_output": False,
        "tool_calling": True,
        "attachment": False,
        "temperature": True,
    },
    "mercury-edit": {
        "name": "Mercury Edit",
        "release_date": "2026-02-24",
        "last_updated": "2026-02-24",
        "open_weights": False,
        "max_input_tokens": 128000,
        "max_output_tokens": 8192,
        "text_inputs": True,
        "image_inputs": False,
        "audio_inputs": False,
        "video_inputs": False,
        "text_outputs": True,
        "image_outputs": False,
        "audio_outputs": False,
        "video_outputs": False,
        "reasoning_output": True,
        "tool_calling": False,
        "attachment": False,
        "temperature": True,
    },
}
